### ISSUE TITLE
new feature: AIX support

### ISSUE THREAD

**Issue by aklyachkin** [hashicorp/go-sockaddr#36]
Adding support for AIX. Just one file, obvious fix, the pull request comes.

**Comment by troytop** [comment]
The fix in #37 worked for me.

**Comment by jtroy** [comment]
Hi, this works for me too. What's left to get it merged? It looks like @sean- reviewed it but it's still in limbo.

**Comment by jtroy** [comment]
I take that back -- it doesn't apply cleanly to master because the build tags need some work. I'll open a PR.

**Comment by schmichael** [comment]
Fixed in #62
