### ISSUE TITLE
go.mod: invalid go version '1.19.0': must match format 1.23

### ISSUE THREAD

**Issue by nunotexbsd** [hashicorp/go-sockaddr#51]
Getting errors from go.mod:
`invalid go version '1.19.0': must match format 1.23`

Shouldn't it be `1.19` instead of `1.19.0`?

**Comment by jefferai** [comment]
Huh, what version of Go are you using? While I agree that that's the normal version string I would expect, the version string was added via `go mod tidy` and then moved back to 1.19.0 from 1.21.0.

I'm guessing this is a newer change for Go but not compatible with older Go versions.

I'll set this back and bump tag.
